# Generated by Django 3.1.4 on 2021-04-26 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myappbd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 12, 26, 47, 730821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homeworkresult',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 12, 26, 47, 746465, tzinfo=utc)),
        ),
    ]
